### ISSUE TITLE
Possible issue with Python 3.11 works with Python3.9

### ISSUE THREAD

**Issue by sidieje** [warhammerkid/bluetti_mqtt#128]
**I moved from pi4 pi OS to tablet running Debian 12.
sudo apt install python3-pip -y installed python3.11
when starting bluetti-mqtt it doesn't start and the below crash is reported.**

`bluetti-mqtt --broker 192.168.1.193 --username ###### --password ##### --interval 5 ########
We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
2025-01-20 13:00:54 INFO     Connecting to MQTT broker...
2025-01-20 13:00:54 INFO     Starting to poll clients...
2025-01-20 13:00:54 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bluetti_mqtt/mqtt_client.py", line 513, in run
    async with Client(
               ^^^^^^^
  File "/home/sideeffect/.local/lib/python3.11/site-packages/asyncio_mqtt/client.py", line 349, in __init__
    self._client.message_retry_set(message_retry_set)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'message_retry_set'
2025-01-20 13:00:54 INFO     Connecting to clients: ['#######', '#######']
2025-01-20 13:00:54 INFO     Shutting down...
`

**I noticed the pi4 was using python3.9
I copied python3.9 to Debian 12 /.local/lib/
I renamed python3.11 to python3.11.backup
I renamed python3.9 to python3.11 
bluetti-mqtt now starts and works normally  (no errors other than the connection issue which it resolved)**

`bluetti-mqtt --broker 192.168.1.193 --username ####### --password ####### --interval 5 ####### #######
We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
2025-01-20 13:13:48 INFO     Connecting to MQTT broker...
2025-01-20 13:13:48 INFO     Starting to poll clients...
2025-01-20 13:13:48 INFO     Connecting to clients: ['#######', '#######']
2025-01-20 13:13:49 INFO     Connected to MQTT broker
2025-01-20 13:13:49 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
2025-01-20 13:13:54 ERROR    Error connecting to device ##:##:##:**A0:25:D6**:
Traceback (most recent call last):
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bluetti_mqtt/bluetooth/client.py", line 78, in _connect
    await self.client.connect()
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 124, in connect
    device = await BleakScanner.find_device_by_address(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/__init__.py", line 310, in find_device_by_address
    return await cls.find_device_by_filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/__init__.py", line 369, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/__init__.py", line 152, in __aenter__
    await self._backend.start()
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/home/sideeffect/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
2025-01-20 13:13:55 INFO     Connected to device: #######
2025-01-20 13:13:55 INFO     Device D1:BF:5B:13:68:9C has name: AC200M2242000839###
2025-01-20 13:13:56 INFO     Sent discovery message of AC200M-2242000839### to Home Assistant
2025-01-20 13:13:56 INFO     Connected to device: ##:##:##:**A0:25:D6**
2025-01-20 13:13:56 INFO     Device 04:7F:0E:A0:25:D6 has name: AC3002225000400###
2025-01-20 13:13:57 INFO     Sent discovery message of AC300-2225000400### to Home Assistant
`
